### ISSUE TITLE
[ENHANCMENT] Using the .format instead of baking the vars into a string using plusses

### ISSUE THREAD

**Issue by TRSGuy** [pelp/rfb-py#1]
So you could do something like `'Client {} connected!'.format(client)`, instead of doing `'Client ' + client + ' connected'` This will help in the future when strings get a bit longer and it's nice to keep it consistant

**Comment by pelp** [comment]
k thenks

**Comment by TRSGuy** [comment]
@pelp What do you think about this? https://github.com/pelp/rfb-py/pull/2 Does it look okay to you?

**Comment by TRSGuy** [comment]
A pull was made, closing this issue.
